### ISSUE TITLE
Comparing an AbstractBufferedFile (or subclass) with some objects might raise an exception

### ISSUE THREAD

**Issue by giovannipizzi** [fsspec/filesystem_spec#1230]
The [`__eq__` method of `AbstractBufferedFile`](https://github.com/fsspec/filesystem_spec/blob/95eb5f94d3230fcfa95052eef6cad1d951431ff5/fsspec/spec.py#L1553) assumes that the `other` element of the comparison has the `.mode` attribute:

https://github.com/fsspec/filesystem_spec/blob/95eb5f94d3230fcfa95052eef6cad1d951431ff5/fsspec/spec.py#L1553

However, this is not always the case. E.g. one could decide to compare with `b""`. This will raise an exception (for `AbstractBufferedFile` and all its subclasses).
This eventually causes the issue described here inveniosoftware/invenio-app-rdm#2097 when used in combination with `ZipStream` that indeed, internally, makes exactly the check `data != b''`.
We already provided a [PR to `zipstream-ng`](https://github.com/pR0Ps/zipstream-ng/pull/15) to avoid to do that check, but I think that one should also not assume here that `.mode` always exists?

E.g., if we only want to compare with objects that have a mode, and `other` does not have a mode, one should just return False (they are different objects).
E.g. replace the line above with
```python
return self.mode == "rb" and hasattr(other, "mode") and other.mode == "rb" and hash(self) == hash(other)
```
Before me or my colleague @liotf make a pull request, can you please let us know if you agree with the change? Thanks!

**Comment by martindurant** [comment]
I agree, an exception is poor form. It would be reasonable to use hasattr, but maybe isinstance would be better; in any case, one might assume that hash(), alone, factors all these things in.

**Comment by pR0Ps** [comment]
Personally, I would recommend putting a `not isinstance(other, AbstractBufferedFile)` or even `not isinstance(other, type(self))` guard on that function instead of using `hasattr`.

Even if the `other` object has a `mode` attribute, there's no guarantee it represents the same thing as a `AbstractBufferedFile.mode` does. If an `AbstractBufferedFile` shouldn't be considered equal to anything other than itself or a subclass (which seems like what you're aiming for here), it seems logical to have that constraint checked.

(context: I'm the [`zipstream-ng`](https://github.com/pR0Ps/zipstream-ng) maintainer and found this via the PR linked above)
