### ISSUE TITLE
Excuse me what is the difference between `self.loc` and `self.offset` in the `AbstractFileSystem`

### ISSUE THREAD

**Issue by karajan1001** [fsspec/filesystem_spec#1285]
I'm the author of `OSSFileSystem` and I'm confused with these two parameters. For my understanding, I thought the `self.loc` is the location where `file.tell()` should return. But what does the `self.offset` do here?

`self.loc` in 
https://github.com/fsspec/filesystem_spec/blob/386a084ffb7f8194265056e19f53ffd252a89e20/fsspec/spec.py#L1572

`self.offset` in 
https://github.com/fsspec/filesystem_spec/blob/386a084ffb7f8194265056e19f53ffd252a89e20/fsspec/spec.py#L1738-L1740

**Comment by martindurant** [comment]
You are correct about self.loc
self.offset, on the other hand, is the location corresponding to the start of the current write buffer, such that at any time
```
self.loc == self.tell() == self.offset + self.buffer.tell()
```
(read files have various kinds of cache/buffer, so we do rely on using self.offset for read-mode, which is why we keep track of both attributes)

**Comment by karajan1001** [comment]
Can be closed I think. Thank you.
