### ISSUE TITLE
`fsspec.fuse` with s3 hangs

### ISSUE THREAD

**Issue by schmidt-ai** [fsspec/filesystem_spec#1408]
I am trying to mount `s3://BUCKET/PATH/` to `/checkpoints`. I run `python -m fsspec.fuse -f -r -l fuse.log s3://BUCKET/PATH/ /BUCKET/PATH /checkpoints`. Is this correct?

The command returns successfully, so then I run `ls /checkpoints`, which hangs indefinitely. Nothing is written to `fuse.log` upon issuing the `ls` command. Is this a bug, or a user error?

It may be valuable to add an example of using `fsspec.fuse` with a remote protocol such as s3 to the docs.

**Comment by martindurant** [comment]
Your usage does look OK. Does `/checkpoints` exist and do you have write permissions? You may find that your system wants to scan the contents of the apparently new directory, which can be very slow if the bucket is large. You should *not* be in that particular directory on invocation.
Since you used the `-r` flag, does the `.fuse_ready` debug file ever appear? Have you tried different combinations of `-f` and `-t` ?

**Comment by martindurant** [comment]
> It seems that url is only used to infer the filesystem protocol.

Correct. Most of this code predates decent support for complex URLs, so it will have originally been just "protocol" and "path" arguments.

**Comment by martindurant** [comment]
You should try in python something like
```
>>> import fsspec
>>> fs = fsspec.filesystem("s3")
>>> fs.ls("sagemaker-us-east-1-210070991806/checkpoint")
```
to make sure s3fs is picking up the right creds.
