### ISSUE TITLE
Best practices for testing fsspec applications

### ISSUE THREAD

**Issue by rth** [fsspec/filesystem_spec#1423]
Hi,

thanks for this package! I was wondering if there were some guidelines for writing tests using cloud paths but without actually using the corresponding client mock library? 
For instance for s3  there is https://github.com/getmoto/moto but for other cloud providers such a thing might not exist.

Essentially I'm trying to write some unit tests to ensure that all file open calls go through fsspec in an application, and that path manipulation make sense.

I tried, for instance, registering a new file system mapped to `az://`, in a unit test, but that would load local files,
```py
from fsspec.implementations.local import LocalFileSystem
from fsspec.registry import register_implementation


class TestLocalFileSystem(LocalFileSystem):
    pass

register_implementation("az", TestLocalFileSystem)
```
this mostly works , but for say in `pandas.read_csv` which uses fsspec internally, I get broken paths `/home/user/az:/some_path` so likely that's not a very robust approach.

Any advice about this?

**Comment by martindurant** [comment]
We do try in most cases to use actual storage emulators where possible, since that gives the best testing coverage, and many of the backends have some specific way of making this possible. In a small number of HTTP-based backends, we use vcrpy to "record" requests the the real API (the author having an appropriate token) which are then replayed during tests minus any sensitive information.

We often use the memory filesystem to emulate "non local" access when testing fsspec internal functionality, but this also has limitations.

For the more general case you are talking about, we don't really have strategy. There are some pieces of filesystem mocks around, but nothing comprehensive. You would probably end up implementing at least some of the spec (e.g., your class should have a `protocol = "az"` attribute to fix paths) and might take some trial and error.

**Comment by rth** [comment]
Thanks for your response!

> You would probably end up implementing at least some of the spec (e.g., your class should have a protocol = "az" attribute to fix paths)

Yes, I ended up with,
```
from fsspec.implementations.local import LocalFileSystem
from fsspec.utils import stringify_path


class TestLocalFileSystem(LocalFileSystem):

    @classmethod
    def _strip_protocol(cls, path):
        path = stringify_path(path)
        if path.startswith("az://"):
            path = path[5:]
        return path
```
which works well enough for my purpose. But I imagine setting protocol is simpler. 

Closing as no action needed. Thanks!
