### ISSUE TITLE
Asyncio spec?

### ISSUE THREAD

**Issue by michalwols** [fsspec/filesystem_spec#156]
This looks like a great project. With python 2 on the way out are there any plans to define an asyncio version of the spec?

**Comment by martindurant** [comment]
No plans as such, would be happy to see how this might look. Note that that not all backends might be equally well-suited to async. Anything using HTTP should work well, though.

Also, it's worth pointing out that fsspec is commonly used in conjunction with Dask, which has its own thread/process/distributed model of running tasks, so data transfer is normally in parallel in that case.

**Comment by michalwols** [comment]
Thanks for the quick reply. 

Partial support makes sense, personally I'd only really need it for cloud storage backends. 

Dask distributed/futures seems like a great alternative for now. I was just looking into using it to offload model inference so using it for blocking io should be easy to do as well.

**Comment by efiop** [comment]
@martindurant @michalwols Looks like this could be closed? https://github.com/fsspec/filesystem_spec/blob/master/fsspec/asyn.py

**Comment by Pursuer2** [comment]
Current async methods are all named with single underscore prefix.  which also indicate the method is internal.   Will "public" methods like async_ls async_cat_fill  be added in future?

**Comment by martindurant** [comment]
It's an open question of style, and I don't have a super strong feeling. Currently, async methods are wrapped into corresponding sync methods based on the names like: `ls = sync_wrapper(_ls)`, so that you can call an async implementation's methods from sync code. 
Other methods like `open_async` (only for HTTP so far) are never intended for use in sync code - `open` is distinct.
