### ISSUE TITLE
Result of `fsspec.open` should subclass `io.BufferedIOBase`

### ISSUE THREAD

**Issue by stinodego** [fsspec/filesystem_spec#1583]
Using Python's built-in `open(mode='rb')`, the result will subclass `io.BufferedIOBase`. Using fsspec's `open` method doesn't:

```python
import io
import fsspec

with open("test.txt", mode="w") as f:
    f.write("hello world")

with open("test.txt", mode="rb") as f:
    print(isinstance(f, io.BufferedIOBase))  # True

with fsspec.open("test.txt", mode="rb") as f:
    print(isinstance(f, io.BufferedIOBase))  # False
```

Using `mode='r'` will result in a `io.TextIOBase` for both methods, as I would expect.

I would expect opening with `mode='rb'` to either subclass `BufferedIOBase` or `RawIOBase`. For context, see the Python io module docs:
https://docs.python.org/3/library/io.html

This issue popped up here https://github.com/pola-rs/polars/issues/15760

**Comment by martindurant** [comment]
I cannot immediately find the issue, but in the past this was the case, and it cause issues with some of the upstream methods/attributes we don't need, such as `__fspath__()` and `fh` which are used by calling code that expects a real file, not just a file-like. This is python, and our files do quack and walk like files, so that should be enough. Some code explicitly checks for read()/write() (or readable(), ...) methods.

**Comment by stinodego** [comment]
I would argue that an `fsspec` opened file doesn't quick and walk like a file. At least, not exactly, as demonstrated in this issue.

Since it _does_ subclass `IOBase`, I would expect it to subclass the correct 'version' of `IOBase` too.

In any case, thanks for your response. Feel free to close this as 'not planned'.
