### ISSUE TITLE
OpenFile.open() fails if the underlying file-like object has read-only attributes

### ISSUE THREAD

**Issue by lhoestq** [fsspec/filesystem_spec#725]
Hi ! First, thanks for this amazing lib :)

Here is my issue:

The zstd decompressor has read only attributes, so I'm having this error in fsspec==2021.7.0 and zstandard==0.15.2:

```python
import fsspec

url = "https://the-eye.eu/public/AI/pile/test.jsonl.zst"
f = fsspec.open(url, "rb", compression="zstd").open()
```
raises
```python
File "/Users/user/.virtualenvs/fsspec-dev/lib/python3.7/site-packages/fsspec/core.py", line 145, in open
    out.close = close
AttributeError: 'zstd.ZstdDecompressionReader' object attribute 'close' is read-only
```
This error appears only if we use `.open()`, not if we use a `with` context.

Note that even if this error is patched, there is another error when reading a zstd file in "rb" mode that raises `UnsupportedOperation` but this is unrelated to `fsspec`. See https://github.com/indygreg/python-zstandard/issues/136

**Comment by martindurant** [comment]
I am not sure what to d about this, but let me explain why the code attempts to overwrite the `close` method. 

When the file-like produced by an OpenFile is closed, we need to make sure to close its internal files too (there can be a few of these, binary file, compression, text encoding). This does not coincide with the lifetime of the OpenFile (in your example it was immediately forgotten before the file is even used). When used with a context, we know when close should be called on the pieces (and the OpenFile is kept alive by the context itself).

One possible alternative is to use `weakref.finalize` to tie closing things to the dropping of the last reference to the file-like (which usually happens when or shortly after it gets closed).

**Comment by lhoestq** [comment]
I can see the point of replacing `close` in this case.

Maybe we could just wrap the file so that we can replace the `close` method without touching the underlying `zstd.ZstdDecompressionReader` ?

For example if you open the file in "r" mode, the `zstd.ZstdDecompressionReader` is wrapped by io.TextIOWrapper so the `close` method can be replaced without issues. In "rb" mode we could just use a bare-bone wrapper like this that allows `close` to be replaced:

```python

class WrappedFile:
    def __init__(self, file):
        self._file = file  # this file object can have read-only attributes

    def __getattr__(self, attr):
        return getattr(self._file, attr)
```
(we may need to add `__enter__`, `__exit__`, `__next__` and `__iter__` as well to make it a file like object)

Let me know what you think or if you have other ideas

**Comment by martindurant** [comment]
Yes, that could work - we'd either want to do it for all files, or catch the `AttributeError` and only do it when needed. The produced file had better implement the whole of `io.IOBase` (not through `__getattr__`), so it would be quite cumbersome - or some appropriate metaclass trick that achieves the same. We would want to ensure that this object is still pickleable, if possible.

**Comment by martindurant** [comment]
@lhoestq , do you think you'd like to try to solve this?
