### ISSUE TITLE
Support operations necessary for memmap

### ISSUE THREAD

**Issue by rom1504** [fsspec/filesystem_spec#832]
Hello,
I've started using fsspec for https://github.com/criteo/autofaiss and it works well. The use case is to read embeddings stored as parquet or numpy over any filesystem.
Before integrating the package I was using Memmap option of np.load which allowed only reading the necessary part in memory instead of everything (basically reading chunk by chunk with a fixed chunk size), hence decreasing memory usage.

With fsspec this doesn't work, operations necessary for memmap do not exist on the file-like returned by fsspec.
I understand trying to read very small parts over some filesystems would be slow, however being able to read medium-sized parts can be fast.

Do you think it could make sense for fsspec to expose operations necessary for memmapping ? Or even be possible at all ?

In particular numpy Memmap is trying to access f.fileno()

https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/memmap.py#L267

More generally my question is whether there would be some way to get a memory mapped byte array from fsspec API.
Combining with https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=cache#caching-files-locally I think it could then fit my use case

Edit:
I ended up doing this https://github.com/criteo/autofaiss/pull/28/commits/641ffdb920d5fbc6b2d339717e85692a3d729b03 (using .read to read only piece by piece).
However I believe it could be possible to do this better by exposing a buffer-like from fsspec that could call read or call mmap depending on the underlying implementation

**Comment by martindurant** [comment]
memory mapping a file in fundamentally an OS-level operation. None of the file-like objects created by fsspec (except LocalFiles) have actualy open file handles, so the information needed for `fileno` does not exist. Basically, fsspec always handles bytes chunks from remote files, and emulates random access with buffering. The numpy [..] slicing is translated into file seek/load calls, but that happens either in the numpy C layer or in the OS kernel.

Regarding local caching: yes, of course that can work, because it gives you a real file on your local filesystem to pass to the OS. It does mean downloading the whole file.

I'm not certain what your commit does (sorry), but I recognise that it should be possible to mirror the numpy [..] access pattern to fetch only needed bytes. In fact, dask.array effectively does this, although there the purpose is to delay, chunk and parallelize the whole computation graph, not just the array access.

**Comment by rom1504** [comment]
thanks!
