### ISSUE TITLE
Is there a way to "change directory" using fsspec?

### ISSUE THREAD

**Issue by benlindsay** [fsspec/filesystem_spec#837]
fsspec is great and I'm excited to start diving into it! Just trying to figure one thing out. Sorry if this is somewhere in the documentation and I missed it, but I'm looking for way to change the root directory of a filesystem using fsspec. I know PyFilesystem2 can do this (see [here](https://docs.pyfilesystem.org/en/latest/guide.html#sub-directories)) but I don't see a similar feature using fsspec. Is there some way to do something like this:

```python
import fsspec

fs = fsspec.filesystem("abfs")
sub_fs = fs.opendir("my-azure-container")
```

and then use `sub_fs` without having to include `"my-azure-container/"` at the beginning of all my blob file paths?

**Comment by martindurant** [comment]
You have two options:

- https://github.com/fsspec/filesystem_spec/pull/745 , an unfinished PR which provides a filesystem that adds a root path to every operation
- https://github.com/Quansight/universal_pathlib , a pathlib.Path implementation on top of fsspec.

There is, otherwise, no concept of "current directory" in fsspec, we generally work with full URLs.

**Comment by benlindsay** [comment]
@martindurant Wow, thanks for the super-fast reply! I subscribed to that PrefixFileSystem PR, that looks like exactly what I want as soon as it's done. In the meantime, I'll probably just write my own (very) light wrapper similar to that one since for now I only need a few of fsspec's methods.

**Comment by martindurant** [comment]
Please express your interest on the PR so we can get some momentum to finish it off.

**Comment by benlindsay** [comment]
Done, thanks again for your help!
