### ISSUE TITLE
filesystem.get mixes up filenames (when using GitHub)

### ISSUE THREAD

**Issue by FirefoxMetzger** [fsspec/filesystem_spec#897]
Disclaimer: I might be going about this the wrong way. If I do, please enlighten me :D

I have the following snippet which (I hoped) would copy 3 files from a remote into a local folder:

```python
fs = fsspec.filesystem("github", org="githubtraining", repo="hellogitworld")
fs.get(
    ["README.txt", "/resources/labels.properties", "/src/test/java/com/github/AppTest.java"],
    ["README.txt", "labels.properties", "AppTest.java")],
)
```

It does copy the content of the three files; however the order is mixed up. I.e., the copying happens as follows (order: remote --> local):

- "README.txt" --> "AppTest.java"
- "/resources/labels.properties" --> "README.txt"
- "/src/test/java/com/github/AppTest.java" --> "labels.properties"

I haven't dug into the source of fsspec, but my hunch is that it has to do with GH having a different order of files remotely than what is listed in the query.

Is this intended behavior? If so, what is the rationale behind it?

**Comment by martindurant** [comment]
I agree with your analysis, probably fsspec is assuming the ordering of files somewhere, but this is not the case for the returned files. It is *not* the intended behaviour. Do you think you have the time to try to find the problem?

**Comment by FirefoxMetzger** [comment]
@martindurant Maybe 😅 I have a deadline on Thursday next week, so no time to investigate until then. If I remember (or you ping me) on the weekend after that, then yes I can look into that.

**Comment by martindurant** [comment]
No rush, I haven't had any other complaints about this. I assume most people access single specific files with the github backend (so no problem with ordering) or, if they want many files, just clone the repo.

**Comment by merrysailor** [comment]
Hello,

I believe the problem is in `AsyncFileSystem._get` and this line:
rpaths = await self._expand_path(rpath, recursive=recursive)

because in `AsyncFileSystem.expand_path` the rpath(s) are added to a set that is subsequently sorted alphanumerically.

Is it possible to address this please? IMHO it is a serious bug in what is very useful functionality, i.e., getting files in bulk from http-like filesystems, not just github, and likely also affects _copy & _cat.

Thank you.

**Comment by martindurant** [comment]
Do I understand you have a fix in mind, or at least a test case that demonstrated the problem? @merrysailor

**Comment by merrysailor** [comment]
Hi,

please see a pytest-style test that fails. The same issue affects Async files systems, even though they go down a different but similar code path. Unfortunately I can't contribute an actual fix in the short term and I can't immediately see a trivial fix. I feel the support of file lists is more of an afterthought, most of the attention being focused on a single file/glob. My gut feeling is that the right/future-proof way to handle lists is to work on a single pair of remote/local file/glob at a time, something along the lines of

```
for remote, local in zip(remotes, locals):
    remote = self.expand_paths(remote)
    local = other_paths(remote, local)
    for p1, p2 in zip(remote, local):
        continue
```


rather than try to expand/join all inputs at the same time.

Thank you.

```
def test_get_copy():
    import fsspec
    import tempfile
    import os

    fs = fsspec.filesystem('file')
    with tempfile.TemporaryDirectory() as tmp_dir:
        foo_fname = os.path.join(tmp_dir, 'foo')
        with open(foo_fname, 'wt') as f:
            f.write('foo')

        bar_fname = os.path.join(tmp_dir, 'bar')
        with open(bar_fname, 'wt') as f:
            f.write('bar')

        ############################

        foo_fname_get = foo_fname + '.1'
        bar_fname_get = bar_fname + '.1'

        fs.get([foo_fname, bar_fname], [foo_fname_get, bar_fname_get])

        ############################

        foo_fname_copy = foo_fname + '.2'
        bar_fname_copy = bar_fname + '.2'

        fs.get([foo_fname, bar_fname], [foo_fname_copy, bar_fname_copy])

        ############################

        with open(foo_fname_get, 'rt') as f:
            assert f.read() == 'foo'  # gets 'bar'

        with open(bar_fname_get, 'rt') as f:
            assert f.read() == 'bar'  # gets 'foo'

        with open(foo_fname_copy, 'rt') as f:
            assert f.read() == 'foo'  # gets 'bar'

        with open(bar_fname_copy, 'rt') as f:
            assert f.read() == 'bar'  # gets 'foo'

        # gets [bar_fname, foo_fname]
        assert fs.expand_path([foo_fname, bar_fname]) == [foo_fname, bar_fname]

```

**Comment by martindurant** [comment]
Thanks for the test case! I will look at this early next week if no one gets to it, and put out a release when fixed.

**Comment by martindurant** [comment]
cc @ianthomas23 - an old issue that seems to still be live and fits with what you've been working on.
